services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample
